### ISSUE TITLE
Cannot find module './Descriptor'

### ISSUE THREAD

**Issue by jamen** [stackgl/glsl-transpiler#28]
When trying to run tests on [`audio-shader`](https://github.com/audiojs/audio-shader) I get an error:
```
Error: Cannot find module './Descriptor'                                                                           
    at Function.Module._resolveFilename (module.js:440:15)                                                         
    at Function.Module._load (module.js:388:25)                                                                    
    at Module.require (module.js:468:17)                                                                           
    at require (internal/module.js:20:19)                                                                          
    at Object.<anonymous> (/home/jamen/dev/audiojs/audio-shader/node_modules/glsl-transpiler/lib/operators.js:7:18)
```

**Comment by dfcreative** [comment]
Updated, from now on should work. Open if not.
