### ISSUE TITLE
Error: did not use all tokens

### ISSUE THREAD

**Issue by 1chandu** [stackgl/glsl-transpiler#39]
Error:
```
not ok 2 Error: did not use all tokens
index.js:13   ---
index.js:13     operator: error
index.js:13     expected: |-
index.js:13       undefined
index.js:13     actual: |-
index.js:13       [Error: did not use all tokens]
index.js:13     stack: |-
index.js:13       Error: did not use all tokens
index.js:13           at ./node_modules/glsl-parser/lib/expr.js.module.exports (http://localhost:8080/bundle.js:59707:11)
index.js:13           at parseexpr (http://localhost:8080/bundle.js:60467:9)
index.js:13           at parse_expr (http://localhost:8080/bundle.js:60444:14)
index.js:13           at write (http://localhost:8080/bundle.js:60054:18)
index.js:13           at reader (http://localhost:8080/bundle.js:60028:5)
index.js:13           at parseArray (http://localhost:8080/bundle.js:59571:5)
index.js:13           at GLSL.parse (http://localhost:8080/bundle.js:63773:9)
index.js:13           at GLSL.compile (http://localhost:8080/bundle.js:62168:13)
```

shader source :

```


vec2 sin_taylor_fp64(vec2 a) {
  vec2 r, s, t, x;

  if (a.x == 0.0 && a.y == 0.0) {
    return vec2(0.0, 0.0);
  }

  x = -mul_fp64(a, a);
  s = a;
  r = a;

  r = mul_fp64(r, x);
  t = mul_fp64(r, INVERSE_FACTORIAL_3_FP64);
  s = sum_fp64(s, t);

  r = mul_fp64(r, x);
  t = mul_fp64(r, INVERSE_FACTORIAL_5_FP64);
  s = sum_fp64(s, t);

  /* keep the following commented code in case we need them
  for extra accuracy from the Taylor expansion*/

  // r = mul_fp64(r, x);
  // t = mul_fp64(r, INVERSE_FACTORIAL_7_FP64);
  // s = sum_fp64(s, t);

  // r = mul_fp64(r, x);
  // t = mul_fp64(r, INVERSE_FACTORIAL_9_FP64);
  // s = sum_fp64(s, t);

  return s;
}

vec2 cos_taylor_fp64(vec2 a) {
  vec2 r, s, t, x;

  if (a.x == 0.0 && a.y == 0.0) {
    return vec2(1.0, 0.0);
  }

  x = -mul_fp64(a, a);
  r = x;
  s = sum_fp64(vec2(1.0, 0.0), r * 0.5);

  r = mul_fp64(r, x);
  t = mul_fp64(r, INVERSE_FACTORIAL_4_FP64);
  s = sum_fp64(s, t);

  r = mul_fp64(r, x);
  t = mul_fp64(r, INVERSE_FACTORIAL_6_FP64);
  s = sum_fp64(s, t);

  /* keep the following commented code in case we need them
  for extra accuracy from the Taylor expansion*/

  // r = mul_fp64(r, x);
  // t = mul_fp64(r, INVERSE_FACTORIAL_8_FP64);
  // s = sum_fp64(s, t);

  // r = mul_fp64(r, x);
  // t = mul_fp64(r, INVERSE_FACTORIAL_10_FP64);
  // s = sum_fp64(s, t);

  return s;
}
```

**Comment by 1chandu** [comment]
Updated with smaller shader version.

**Comment by Pessimistress** [comment]
Temporary work around: by removing all the comments the above shader code is transpiled correctly.

**Comment by iY0Yi** [comment]
Hi. I got the same error on this code.
```
// https://www.shadertoy.com/view/XdGfRR
#define UI0 1597334673U
#define UI1 3812015801U
#define UI2 uvec2(UI0, UI1)
#define UI3 uvec3(UI0, UI1, 2798796415U)
#define UI4 uvec4(UI3, 1979697957U)
#define UIF (1.0 / float(0xffffffffU))

vec3 hash33(vec3 p){
	uvec3 q = uvec3(ivec3(p)) * UI3;
	q = (q.x ^ q.y ^ q.z)*UI3;
	return vec3(q) * UIF;
}

vec3 v = hash33(vec3(1));
```

and i extracted this is minimal one.
`uvec2 n = uvec2(1);`

tested on the playground and my app.

**Comment by dy** [comment]
oh, my. That belongs to glsl-parser.

**Comment by dy** [comment]
Ok, that seems to be because glsl-tokenizer expects 300es instead regular one.

**Comment by dy** [comment]
@iY0Yi to compile that code `uvec2 n = uvec2(1);` you need too pass `{version: '300 es'}` to options:

```js
var compile = GLSL({version: '300 es'})
	t.equal(clean(compile(t.name)),
	clean`function int (val) {
		return val|0;
	}
	var n = [1, 1].map(uint);`)
```

**Comment by iY0Yi** [comment]
@dy
thanks. but i got different error message with '300 es'.
`uvec2 n = uvec2(1);`
> uint is not defined
> function int (val) {
> 	return val|0;
> }
> var n = [1, 1].map(uint);

and if i try the above `hash33` code,
> expected `)`, got `U` at line 10

i'll try to figure out the cause too.

**Comment by dy** [comment]
@iY0Yi good catch! Fixed in v2.0.2. Thank you!
